### ISSUE TITLE
listing on "MDAnalysis: used by page"?

### ISSUE THREAD

**Issue by orbeckst** [drorlab/pensa#1]
@martinvoegele , if you would like PENSA listed at https://www.mdanalysis.org/pages/used-by/ then the MDAnalysis folks would be more than happy to work with you to add it.

You could create a PR in https://github.com/MDAnalysis/MDAnalysis.github.io/ , specifically, by just editing https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/pages/used-by.md or raise an issue in https://github.com/MDAnalysis/MDAnalysis.github.io/issues with the text to be inserted. 

All the best!

**Comment by martinvoegele** [comment]
Hi @orbeckst, thanks a lot! I created a pull request for "used-by.md".
MDAnalysis has been extremely helpful in this project (and much of my other work), so big kudos to you and your team!
